### PR TITLE
PIM-5364: Add new EE mass edit jobs with rules application

### PR DESCRIPTION
**Pull request by grena**
Data generated & tested.

### CODE REVIEW

**Comment by ClementGautier** [comment]
GTM

**Comment by SamirBoulil** [comment]
GTM

**Comment by SamirBoulil** [comment]
Please test out that catalogs can be successfully generated :)

**Comment by solivier** [comment]
gtm

**Comment by pierallard** [comment]
GTM if you execute it one time and try to import generated fixtures ;)

**Pull request merged**
