### PR TITLE
TIP-536: Fix php versions for travis

### PR DESCRIPTION
**Pull request by momoss**
Since pim-community-dev require php >=5.6.0, remove travis check for php 5.4 and 5.5

| Q | A |
| --- | --- |
| Added Specs | N |
| Generate fixtures and install | N |
| Generate products and import | N |
| Review and 2 GTM | Y |
|  Tech Doc | N |

### CODE REVIEW

**Comment by solivier** [comment]
Add ticket number and then GTM

**Comment by momoss** [comment]
There is no ticket...

**Comment by solivier** [comment]
Create a new one or bind it to the ticket number about dropping the php 5.4 version ...

**Comment by momoss** [comment]
Done!

**Comment by skeleton** [comment]
gtm

**Comment by pierallard** [comment]
gtm

**Pull request merged**
